name: CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start MongoDB with Docker Compose
        run: docker-compose up -d

      - name: Install Dependencies with Extended Output Mode
        run: mvn clean install -e

      - name: Run Tests
        run: |
          mvn test
          echo "test passed!"

      - name: Build with Maven
        run: |
          mvn package 
          echo "Success!"